### ISSUE TITLE
Support for different types of unit specs

### ISSUE THREAD

**Issue by faloi** [uqbar-project/mumuki-gobstones-server#31]
In order to be able to test functions and procedures in a unitary way, we need to implement those kind of tests.

My proposal is to add a `target` field to the test definition, with possible values: `program | functionName | ProcedureName`. 

The expected behaviour of the examples would be:
- **program**, the current implementation 
- **procedure**, given a set of arguments and an initial board, it should execute the procedure with the given arguments and compare the final boards
- **function**, given a set of arguments and an initial board, it should evaluate the function with the given arguments and compare the results

**Comment by flbulgarelli** [comment]
I agree with the proposal. I would just rename `target` to `subject` - which is consistent when the meaning of test subject in many specs frameworks.

**Comment by flbulgarelli** [comment]
In addition, you could assume that when no subject is specified, it is `program`. That way we should specify subject only when testing functions and procedures.

**Comment by flbulgarelli** [comment]
Please take into consideration that Gobstones expects procedures to be defined in `UpperCamelCase` and functions in `lowerCamelCase`,  but this is not generally true for every language. In Ruby-Stones, we are using the bang convention, for example. 

It would be nice that:
* either the inference rules are pluggable
* or the `subject` is specified like `{"type": "procedure", "name": "Foo"}`  instead of just `"subject": "Foo"`

**Comment by faloi** [comment]
We can simply delegate the inference to the language then :smile:
